#!/bin/sh

if [ "_$1" = _freebsd-gcc2 ]; then
	cd source
	make -DGCC2 && strip ../mvdsv
elif [ "_$1" = _freebsd-gcc3 ]; then
	cd source
	make -DGCC3 && strip ../mvdsv
elif [ "_$1" = _linux-gcc2 ]; then
	make linux-gcc2 && strip mvdsv
elif [ "_$1" = _linux-gcc3 ]; then
	make linux-gcc3 && strip mvdsv
else
echo ""
echo "You must specify the system which you want to compile for:"
echo ""
echo "./build linux-gcc2        Linux gcc 2.x"
echo "./build linux-gcc3        Linux gcc 3.x"
echo "./build freebsd-gcc2      FreeBSD gcc 2.x"
echo "./build freebsd-gcc3      FreeBSD gcc 3.x"
echo ""
fi
