#!/bin/sh

if [ "_$1" = _freebsd ]; then
	make -f Makefile.FreeBSD && strip mvdsv

elif [ "_$1" = _freebsd-qwdtools ]; then
	cd source/qwdtools
	make && strip ../../qwdtools

elif [ "_$1" = _darwin ]; then
	bsdmake -f Makefile.Darwin && strip mvdsv

elif [ "_$1" = _darwin-qwdtools ]; then
	cd source/qwdtools
	bsdmake && strip ../../qwdtools

elif [ "_$1" = _linux-gcc2 ]; then
	make linux-gcc2 && strip mvdsv

elif [ "_$1" = _linux-gcc2-qwdtools ]; then
	cd source/qwdtools
	make linux-gcc2 && strip ../../qwdtools

elif [ "_$1" = _linux-gcc3 ]; then
	make linux-gcc3 && strip mvdsv

elif [ "_$1" = _linux-gcc3-qwdtools ]; then
	cd source/qwdtools
	make linux-gcc3 && strip ../../qwdtools
else
echo ""
echo "You must specify the system which you want to compile for:"
echo ""
echo "./build freebsd               FreeBSD"
echo "./build freebsd-qwdtools      FreeBSD qwdtools"
echo "./build darwin                darwin/macosx"
echo "./build darwin-qwdtools       darwin/macosx qwdtools"
echo "./build linux-gcc2            Linux gcc 2.x"
echo "./build linux-gcc2-qwdtools   Linux gcc 2.x qwdtools"
echo "./build linux-gcc3            Linux gcc 3.x"
echo "./build linux-gcc3-qwdtools   Linux gcc 3.x qwdtools"
echo ""
fi
